name: Bug Report 🐝
description: Create a bug report to help us improve the action.
title: 'bug: 🐝 '
labels: ['bug 🐝', 'triage ⚠️']
assignees:
  - JamesIves
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the sections below to help us reproduce the issue and improve the action. If you're unsure about something, feel free to skip it or write N/A in the field.

        [Please check the Q&A before posting an issue here](https://github.com/JamesIves/github-sponsors-readme-action/discussions/categories/q-a).
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: 'Please provide a clear and concise description of what the bug is and what you expected to happen.'
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: 'Steps to reproduce the behavior. Please provide a minimal example if possible.'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please provide your deployment logs if applicable. If the error message isn't revealing the problem please set ACTIONS_STEP_DEBUG to true in your repository's secrets menu and run the workflow again."
      render: shell
    validations:
      required: false
  - type: textarea
    id: workflow
    attributes:
      label: Workflow
      description: 'Please provide a link or snippet of your workflow yml file.'
      render: yml
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: 'Add any other context about the problem here that does not fit elsewhere.'
    validations:
      required: false
